### ISSUE TITLE
Feedback from User Journeys Meeting

### ISSUE THREAD

**Issue by jaredsilver** [jaredsilver/oppia-splash-page-mock#2]
- Not geared toward learners enough
- Maybe include some of the lessons on the splash page
- What if we the top lessons as text links just below the browse lessons button?
- Text should be different for browse lessons button
- More concrete stuff should be prioritized more
- Having lessons might be more attractive than texts
- Page is still creator heavy
- Make the text a little more in the space between learners and creators
- Test:
   - Each text box should highlight the interplay between learners and creators
   - Or should we have it more explicit, keeping the two separated vertically
- Let’s make the page more learner-oriented under the assumption that we’ll have changed priorities and have completed math explorations by the time this is implemented
    - Two CTAs: one is learn math, and the other is “help build these lessons”
- Body of the page: large primary action button for browsing lessons
- Somewhere attached to the button: list of top topics
- Another primary action button in the navbar at the top of the screen for creators
- Udemy example
- Use the circle image of the otter
- Or we can put the otter on top
- Otter holding CTA

**Comment by jblair87** [comment]
Suggestion: Teaching text on splash page has a button that leads to a new page with text similar to the about oppia page/ the splash page text (aka a page just for teachers). Not to make things complicated but I feel it might be the right thing to do.

**Comment by jaredsilver** [comment]
one variation: exploration cards on the page w/ the last card being a link to view more

**Comment by jaredsilver** [comment]
generic call to action text until user testing is completed

**Comment by jaredsilver** [comment]
Turn Teach w/ Oppia page into Udemy style page. Do we want to continue the teach w/ oppia program in light of movement toward content drives?

**Comment by jaredsilver** [comment]
Smaller viewport -> circle otter

**Comment by jaredsilver** [comment]
1. Exploration cards section will be in every variation
a. One variation: this section will be on top of the three column section
b. One variation: this section will be below the three column section

2. Text changes:
a. Mission-oriented style of headline and CTAs
b. CTAs will be revisited once we have feedback from user testing

3. For all variants, circle otter on smaller screens

4. Variant w/ two main CTA buttons, variant w/ one learner-focused CTA button, variant w/o main CTA buttons
